joint:
  names: [LINK_0, LINK_1, LINK_2, LINK_3, LINK_4]
motion:
  names: [pos0, pos1, pos2]
  pos0:
    step: [0.00, 0.00, 0.00, 0.00, 0.00]  # radian
    time_from_start: 1.0
  pos1:
    step: [0.20, 0.20, 0.20, 0.20, 0.20]  # radian
    time_from_start: 2.0
  pos2:
    step: [0.00, 0.00, 0.00, 0.00, 0.00]  # radian
    time_from_start: 3.0
